FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o app .

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /app/app .
COPY --from=builder /app/public ./public

RUN mkdir -p public/struk public/tmp

EXPOSE 8081

CMD ["./app"]