// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "golang-mmi/internal/model"

	mock "github.com/stretchr/testify/mock"

	repository "golang-mmi/internal/repository"
)

// RealisasiBonRepository is an autogenerated mock type for the RealisasiBonRepository type
type RealisasiBonRepository struct {
	mock.Mock
}

// ApproveRBS provides a mock function with given fields: ctx, p
func (_m *RealisasiBonRepository) ApproveRBS(ctx context.Context, p repository.ApproveRBSResponse) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for ApproveRBS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ApproveRBSResponse) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRealisasiBon provides a mock function with given fields: ctx, realisasiBon
func (_m *RealisasiBonRepository) CreateRealisasiBon(ctx context.Context, realisasiBon *model.RealisasiBonSementara) error {
	ret := _m.Called(ctx, realisasiBon)

	if len(ret) == 0 {
		panic("no return value specified for CreateRealisasiBon")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RealisasiBonSementara) error); ok {
		r0 = rf(ctx, realisasiBon)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeclineRBS provides a mock function with given fields: ctx, p
func (_m *RealisasiBonRepository) DeclineRBS(ctx context.Context, p repository.DeclineRBSResponse) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for DeclineRBS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeclineRBSResponse) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDetailRBS provides a mock function with given fields: ctx, rbsid
func (_m *RealisasiBonRepository) GetDetailRBS(ctx context.Context, rbsid uint) (model.RealisasiBonSementara, error) {
	ret := _m.Called(ctx, rbsid)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailRBS")
	}

	var r0 model.RealisasiBonSementara
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (model.RealisasiBonSementara, error)); ok {
		return rf(ctx, rbsid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) model.RealisasiBonSementara); ok {
		r0 = rf(ctx, rbsid)
	} else {
		r0 = ret.Get(0).(model.RealisasiBonSementara)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, rbsid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListPendingRBS provides a mock function with given fields: ctx, jabatan, userID
func (_m *RealisasiBonRepository) GetListPendingRBS(ctx context.Context, jabatan string, userID uint) ([]model.RealisasiBonSementara, error) {
	ret := _m.Called(ctx, jabatan, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetListPendingRBS")
	}

	var r0 []model.RealisasiBonSementara
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) ([]model.RealisasiBonSementara, error)); ok {
		return rf(ctx, jabatan, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) []model.RealisasiBonSementara); ok {
		r0 = rf(ctx, jabatan, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RealisasiBonSementara)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, jabatan, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListRiwayatRealisasiBon provides a mock function with given fields: ctx, page, limit, f
func (_m *RealisasiBonRepository) GetListRiwayatRealisasiBon(ctx context.Context, page int, limit int, f repository.FilterRBS) ([]repository.RiwayatRBSResponse, int64, int64, error) {
	ret := _m.Called(ctx, page, limit, f)

	if len(ret) == 0 {
		panic("no return value specified for GetListRiwayatRealisasiBon")
	}

	var r0 []repository.RiwayatRBSResponse
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, repository.FilterRBS) ([]repository.RiwayatRBSResponse, int64, int64, error)); ok {
		return rf(ctx, page, limit, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, repository.FilterRBS) []repository.RiwayatRBSResponse); ok {
		r0 = rf(ctx, page, limit, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.RiwayatRBSResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, repository.FilterRBS) int64); ok {
		r1 = rf(ctx, page, limit, f)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, repository.FilterRBS) int64); ok {
		r2 = rf(ctx, page, limit, f)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, int, int, repository.FilterRBS) error); ok {
		r3 = rf(ctx, page, limit, f)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetListRiwayatRealisasiBonById provides a mock function with given fields: ctx, page, limit, userID
func (_m *RealisasiBonRepository) GetListRiwayatRealisasiBonById(ctx context.Context, page int, limit int, userID uint) ([]repository.RiwayatRBSResponse, int64, int64, error) {
	ret := _m.Called(ctx, page, limit, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetListRiwayatRealisasiBonById")
	}

	var r0 []repository.RiwayatRBSResponse
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, uint) ([]repository.RiwayatRBSResponse, int64, int64, error)); ok {
		return rf(ctx, page, limit, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, uint) []repository.RiwayatRBSResponse); ok {
		r0 = rf(ctx, page, limit, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.RiwayatRBSResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, uint) int64); ok {
		r1 = rf(ctx, page, limit, userID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, uint) int64); ok {
		r2 = rf(ctx, page, limit, userID)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, int, int, uint) error); ok {
		r3 = rf(ctx, page, limit, userID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetStatusRBS provides a mock function with given fields: ctx, rbsid
func (_m *RealisasiBonRepository) GetStatusRBS(ctx context.Context, rbsid uint) (string, error) {
	ret := _m.Called(ctx, rbsid)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusRBS")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (string, error)); ok {
		return rf(ctx, rbsid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) string); ok {
		r0 = rf(ctx, rbsid)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, rbsid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRealisasiBonRepository creates a new instance of RealisasiBonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRealisasiBonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RealisasiBonRepository {
	mock := &RealisasiBonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
