// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "golang-mmi/internal/model"
	 "golang-mmi/internal/dto"

	mock "github.com/stretchr/testify/mock"

	repository "golang-mmi/internal/repository"
)

// PerjalananDinasRepository is an autogenerated mock type for the PerjalananDinasRepository type
type PerjalananDinasRepository struct {
	mock.Mock
}

// ApprovePerjalananDinas provides a mock function with given fields: ctx, p
func (_m *PerjalananDinasRepository) ApprovePerjalananDinas(ctx context.Context, p repository.ApprovePerjalananDinasparams) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for ApprovePerjalananDinas")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ApprovePerjalananDinasparams) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePengajuanPerjalanaDinas provides a mock function with given fields: ctx, perjalananDinas
func (_m *PerjalananDinasRepository) CreatePengajuanPerjalanaDinas(ctx context.Context, perjalananDinas *model.RequestPPD) error {
	ret := _m.Called(ctx, perjalananDinas)

	if len(ret) == 0 {
		panic("no return value specified for CreatePengajuanPerjalanaDinas")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RequestPPD) error); ok {
		r0 = rf(ctx, perjalananDinas)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeclinePerjalananDinas provides a mock function with given fields: ctx, p
func (_m *PerjalananDinasRepository) DeclinePerjalananDinas(ctx context.Context, p repository.DeclinePerjalananDinasParams) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for DeclinePerjalananDinas")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeclinePerjalananDinasParams) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDetailPerjalananDinas provides a mock function with given fields: ctx, ppdid
func (_m *PerjalananDinasRepository) GetDetailPerjalananDinas(ctx context.Context, ppdid uint) (model.RequestPPD, error) {
	ret := _m.Called(ctx, ppdid)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailPerjalananDinas")
	}

	var r0 model.RequestPPD
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (model.RequestPPD, error)); ok {
		return rf(ctx, ppdid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) model.RequestPPD); ok {
		r0 = rf(ctx, ppdid)
	} else {
		r0 = ret.Get(0).(model.RequestPPD)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, ppdid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastNomorDokumenGeneral provides a mock function with given fields: ctx, pattern
func (_m *PerjalananDinasRepository) GetLastNomorDokumenGeneral(ctx context.Context, pattern string) (string, error) {
	ret := _m.Called(ctx, pattern)

	if len(ret) == 0 {
		panic("no return value specified for GetLastNomorDokumenGeneral")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, pattern)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, pattern)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pattern)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastNomorDokumenSpecific provides a mock function with given fields: ctx, tipe, pattern
func (_m *PerjalananDinasRepository) GetLastNomorDokumenSpecific(ctx context.Context, tipe string, pattern string) (string, error) {
	ret := _m.Called(ctx, tipe, pattern)

	if len(ret) == 0 {
		panic("no return value specified for GetLastNomorDokumenSpecific")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, tipe, pattern)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, tipe, pattern)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tipe, pattern)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListPPDForRealisasi provides a mock function with given fields: ctx, userID
func (_m *PerjalananDinasRepository) GetListPPDForRealisasi(ctx context.Context, userID uint) ([]dto.DropdownPPDResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetListPPDForRealisasi")
	}

	var r0 []dto.DropdownPPDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]dto.DropdownPPDResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []dto.DropdownPPDResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.DropdownPPDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListPendingPerjalananDinas provides a mock function with given fields: ctx, jabatan, userID
func (_m *PerjalananDinasRepository) GetListPendingPerjalananDinas(ctx context.Context, jabatan string, userID uint) ([]dto.ListPPDResponse, error) {
	ret := _m.Called(ctx, jabatan, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetListPendingPerjalananDinas")
	}

	var r0 []dto.ListPPDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) ([]dto.ListPPDResponse, error)); ok {
		return rf(ctx, jabatan, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) []dto.ListPPDResponse); ok {
		r0 = rf(ctx, jabatan, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ListPPDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, jabatan, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListRiwayatPerjalananDinas provides a mock function with given fields: ctx, page, limit
func (_m *PerjalananDinasRepository) GetListRiwayatPerjalananDinas(ctx context.Context, page int, limit int) ([]dto.ListPPDResponse, int64, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetListRiwayatPerjalananDinas")
	}

	var r0 []dto.ListPPDResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]dto.ListPPDResponse, int64, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []dto.ListPPDResponse); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ListPPDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetListRiwayatPerjalananDinasByAtasan provides a mock function with given fields: ctx, userID, page, limit
func (_m *PerjalananDinasRepository) GetListRiwayatPerjalananDinasByAtasan(ctx context.Context, userID uint, page int, limit int) ([]dto.ListPPDResponse, int64, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetListRiwayatPerjalananDinasByAtasan")
	}

	var r0 []dto.ListPPDResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) ([]dto.ListPPDResponse, int64, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) []dto.ListPPDResponse); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ListPPDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, int, int) int64); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, int, int) error); ok {
		r2 = rf(ctx, userID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetListRiwayatPerjalananDinasByUserID provides a mock function with given fields: ctx, userID, page, limit
func (_m *PerjalananDinasRepository) GetListRiwayatPerjalananDinasByUserID(ctx context.Context, userID uint, page int, limit int) ([]dto.ListPPDResponse, int64, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetListRiwayatPerjalananDinasByUserID")
	}

	var r0 []dto.ListPPDResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) ([]dto.ListPPDResponse, int64, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) []dto.ListPPDResponse); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ListPPDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, int, int) int64); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, int, int) error); ok {
		r2 = rf(ctx, userID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetStatusPerjalananDinas provides a mock function with given fields: ctx, ppdid
func (_m *PerjalananDinasRepository) GetStatusPerjalananDinas(ctx context.Context, ppdid uint) (string, error) {
	ret := _m.Called(ctx, ppdid)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusPerjalananDinas")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (string, error)); ok {
		return rf(ctx, ppdid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) string); ok {
		r0 = rf(ctx, ppdid)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, ppdid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPerjalananDinasRepository creates a new instance of PerjalananDinasRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPerjalananDinasRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PerjalananDinasRepository {
	mock := &PerjalananDinasRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
