// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "golang-mmi/internal/model"
	"golang-mmi/internal/dto"

	mock "github.com/stretchr/testify/mock"

)

// ServiceRBS is an autogenerated mock type for the ServiceRBS type
type ServiceRBS struct {
	mock.Mock
}

// ApproveRBS provides a mock function with given fields: ctx, rbsid, catatan
func (_m *ServiceRBS) ApproveRBS(ctx context.Context, rbsid uint, catatan string) error {
	ret := _m.Called(ctx, rbsid, catatan)

	if len(ret) == 0 {
		panic("no return value specified for ApproveRBS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, rbsid, catatan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRealisasiBon provides a mock function with given fields: ctx, req
func (_m *ServiceRBS) CreateRealisasiBon(ctx context.Context, req *model.RealisasiBonSementara) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRealisasiBon")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RealisasiBonSementara) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeclineRBS provides a mock function with given fields: ctx, ppdid, catatan
func (_m *ServiceRBS) DeclineRBS(ctx context.Context, ppdid uint, catatan string) error {
	ret := _m.Called(ctx, ppdid, catatan)

	if len(ret) == 0 {
		panic("no return value specified for DeclineRBS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, ppdid, catatan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDropdownPPD provides a mock function with given fields: ctx
func (_m *ServiceRBS) GetDropdownPPD(ctx context.Context) ([]dto.DropdownPPDResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDropdownPPD")
	}

	var r0 []dto.DropdownPPDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.DropdownPPDResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.DropdownPPDResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.DropdownPPDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListPendingRBS provides a mock function with given fields: ctx
func (_m *ServiceRBS) GetListPendingRBS(ctx context.Context) ([]model.RealisasiBonSementara, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetListPendingRBS")
	}

	var r0 []model.RealisasiBonSementara
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.RealisasiBonSementara, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.RealisasiBonSementara); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RealisasiBonSementara)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListRBS provides a mock function with given fields: ctx, page, limit, bulan, tahun
func (_m *ServiceRBS) GetListRBS(ctx context.Context, page int, limit int, bulan int, tahun int) ([]dto.ListRBSResponse, int64, int64, error) {
	ret := _m.Called(ctx, page, limit, bulan, tahun)

	if len(ret) == 0 {
		panic("no return value specified for GetListRBS")
	}

	var r0 []dto.ListRBSResponse
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, int) ([]dto.ListRBSResponse, int64, int64, error)); ok {
		return rf(ctx, page, limit, bulan, tahun)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, int) []dto.ListRBSResponse); ok {
		r0 = rf(ctx, page, limit, bulan, tahun)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ListRBSResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int, int) int64); ok {
		r1 = rf(ctx, page, limit, bulan, tahun)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, int, int) int64); ok {
		r2 = rf(ctx, page, limit, bulan, tahun)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, int, int, int, int) error); ok {
		r3 = rf(ctx, page, limit, bulan, tahun)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetListRBSDetail provides a mock function with given fields: ctx, ppdid
func (_m *ServiceRBS) GetListRBSDetail(ctx context.Context, ppdid uint) ([]model.RBSrincian, error) {
	ret := _m.Called(ctx, ppdid)

	if len(ret) == 0 {
		panic("no return value specified for GetListRBSDetail")
	}

	var r0 []model.RBSrincian
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]model.RBSrincian, error)); ok {
		return rf(ctx, ppdid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []model.RBSrincian); ok {
		r0 = rf(ctx, ppdid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RBSrincian)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, ppdid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceRBS creates a new instance of ServiceRBS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceRBS(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceRBS {
	mock := &ServiceRBS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
