// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "golang-mmi/internal/model"
	"golang-mmi/internal/dto"

	mock "github.com/stretchr/testify/mock"

)

// ServicePPD is an autogenerated mock type for the ServicePPD type
type ServicePPD struct {
	mock.Mock
}

// ApprovePerjalananDinas provides a mock function with given fields: ctx, ppdid, catatan
func (_m *ServicePPD) ApprovePerjalananDinas(ctx context.Context, ppdid uint, catatan string) error {
	ret := _m.Called(ctx, ppdid, catatan)

	if len(ret) == 0 {
		panic("no return value specified for ApprovePerjalananDinas")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, ppdid, catatan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePengajuanPerjalanaDinas provides a mock function with given fields: ctx, req
func (_m *ServicePPD) CreatePengajuanPerjalanaDinas(ctx context.Context, req *model.RequestPPD) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePengajuanPerjalanaDinas")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RequestPPD) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeclinePerjalananDinas provides a mock function with given fields: ctx, ppdid, catatan
func (_m *ServicePPD) DeclinePerjalananDinas(ctx context.Context, ppdid uint, catatan string) error {
	ret := _m.Called(ctx, ppdid, catatan)

	if len(ret) == 0 {
		panic("no return value specified for DeclinePerjalananDinas")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, ppdid, catatan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateNomorDokumenGeneral provides a mock function with given fields: ctx, prefix
func (_m *ServicePPD) GenerateNomorDokumenGeneral(ctx context.Context, prefix string) (string, error) {
	ret := _m.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for GenerateNomorDokumenGeneral")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, prefix)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, prefix)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateNomorDokumenSpecific provides a mock function with given fields: ctx, tipe, prefix
func (_m *ServicePPD) GenerateNomorDokumenSpecific(ctx context.Context, tipe string, prefix string) (string, error) {
	ret := _m.Called(ctx, tipe, prefix)

	if len(ret) == 0 {
		panic("no return value specified for GenerateNomorDokumenSpecific")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, tipe, prefix)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, tipe, prefix)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tipe, prefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDropdownPPD provides a mock function with given fields: ctx, userID
func (_m *ServicePPD) GetDropdownPPD(ctx context.Context, userID uint) ([]dto.DropdownPPDResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDropdownPPD")
	}

	var r0 []dto.DropdownPPDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]dto.DropdownPPDResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []dto.DropdownPPDResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.DropdownPPDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListPendingPerjalananDinas provides a mock function with given fields: ctx
func (_m *ServicePPD) GetListPendingPerjalananDinas(ctx context.Context) ([]model.RequestPPD, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetListPendingPerjalananDinas")
	}

	var r0 []model.RequestPPD
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.RequestPPD, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.RequestPPD); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RequestPPD)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListPerjalananDetail provides a mock function with given fields: ctx, ppdid
func (_m *ServicePPD) GetListPerjalananDetail(ctx context.Context, ppdid uint) ([]model.PPDRincianTambahan, error) {
	ret := _m.Called(ctx, ppdid)

	if len(ret) == 0 {
		panic("no return value specified for GetListPerjalananDetail")
	}

	var r0 []model.PPDRincianTambahan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]model.PPDRincianTambahan, error)); ok {
		return rf(ctx, ppdid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []model.PPDRincianTambahan); ok {
		r0 = rf(ctx, ppdid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PPDRincianTambahan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, ppdid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListPerjalananDinas provides a mock function with given fields: ctx, page, limit
func (_m *ServicePPD) GetListPerjalananDinas(ctx context.Context, page int, limit int) ([]dto.ListPPDResponse, int64, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetListPerjalananDinas")
	}

	var r0 []dto.ListPPDResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]dto.ListPPDResponse, int64, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []dto.ListPPDResponse); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ListPPDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewServicePPD creates a new instance of ServicePPD. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServicePPD(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServicePPD {
	mock := &ServicePPD{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
